### ISSUE TITLE
When runner is stopped the worker processes hang around

### ISSUE THREAD

**Issue by dvdotsenko** [dvdotsenko/nose_gevent_multiprocess#4]
For now need to kill them by hand. Need to add clean up to the CTRL+C handling

**Comment by richafrank** [comment]
Should be fixed by https://github.com/dvdotsenko/nose_gevent_multiprocess/pull/6/commits/c43763cde1b25748dd09d80a01c4266f96f5234a and https://github.com/dvdotsenko/nose_gevent_multiprocess/pull/6/commits/acb28779afc33b686692f8db48c440d364d04a29
