### ISSUE TITLE
60-second hang after all workers finish

### ISSUE THREAD

**Issue by jikamens** [dvdotsenko/nose_gevent_multiprocess#5]
After all my workers finish running tests, and the "# clients served within #.# s" message is printed, the main nosetests wrapper process hangs around for 60 more seconds before exiting. No log messages are printed during this wait. When I run strace on it, it's hung on epoll_wait waiting for a thread, and eventually epoll_wait returns and it finishes up.

Any idea what might be causing this and what to do about it?

**Comment by richafrank** [comment]
Should be fixed by https://github.com/dvdotsenko/nose_gevent_multiprocess/pull/6/commits/c43763cde1b25748dd09d80a01c4266f96f5234a
